name: Production
on:
  push:
    branches:
      - 'master'
jobs:
  linter:
    name: Format and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run:  npm install
      - name: Format
        run: npm run prettier-format
      - name: Lint
        run: npm run lint

  build-and-push-image:
    needs: [linter]
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY_URL: registry.gitlab.com/fiuba-memo2/tp2-20221
      CI_IMAGE_REGISTRY: ghcr.io
      CI_OWNER: Taller2-Fiuumber
      CI_IMAGE_NAME: ${{ github.repository }}
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_USERNAME: ${{ github.actor }}
      HEROKU_APP: fiuumber-web
    steps:
      - uses: actions/checkout@master

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.CI_IMAGE_REGISTRY }}
          username: ${{ env.GITHUB_USERNAME }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Get image tag
        env:
          IMAGE_NAME: ${{ env.CI_IMAGE_REGISTRY }}/${{ env.CI_IMAGE_NAME }}
        run: |
          VERSION=$(cat Version.txt)
          IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_TAG=$(echo $IMAGE_NAME:$VERSION)" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t ${{ env.IMAGE_TAG }} .
      - name: Push image to Github Container Registry
        run: docker push ${{ env.IMAGE_TAG }}

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Tag container of Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker tag ${{ env.IMAGE_TAG }} registry.heroku.com/${{ env.HEROKU_APP}}/web

      - name: Push container to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web --app ${{ env.HEROKU_APP}}

      - name: Release container to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app ${{ env.HEROKU_APP}}
